services:
  nginx:
    image: nginx:1.27-alpine
    container_name: ecoride_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ecoride_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - .env.dev
    user: "${UID}:${GID}"
    depends_on:
      - postgresql
      - mongodb

  postgresql:
    image: postgres:16-alpine
    container_name: ecoride_postgresql
    environment:
      POSTGRES_DB: ecoride
      POSTGRES_USER: ecoride
      POSTGRES_PASSWORD: ecoride
    ports:
      - "5432:5432"
    volumes:
      - donnees_postgresql:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: ecoride_mongodb
    ports:
      - "27017:27017"
    volumes:
      - donnees_mongodb:/data/db

volumes:
  donnees_postgresql:
  donnees_mongodb:
