services:
  nginx:
    networks:
      - ecoride_reseau
    image: nginx:1.27-alpine
    container_name: ecoride_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ecoride_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - .env.docker
    environment:
      COMPOSER_HOME: /tmp/composer
      MAILER_DSN: "smtp://mailhog:1025"
    user: "${UID}:${GID}"
    depends_on:
      - postgresql
      - mongodb
    networks:
      - ecoride_reseau


  postgresql:
    image: postgres:16
    container_name: ecoride_postgresql
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - donnees_postgresql:/var/lib/postgresql/data
    networks:
      - ecoride_reseau

  mongodb:
    image: mongo:7
    container_name: ecoride_mongodb
    ports:
      - "27017:27017"
    volumes:
      - donnees_mongodb:/data/db
    networks:
      - ecoride_reseau


  mailhog:
    image: mailhog/mailhog
    container_name: ecoride_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - ecoride_reseau

volumes:
  donnees_postgresql:
  donnees_mongodb:

networks:
  ecoride_reseau:
